name: build docker

on:
  workflow_run:
    workflows: [Release create]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: fetch the binary
        run: echo "${{toJSON(github.event.workflow_run)}}"
