name: Main

on:
  workflow_dispatch:

jobs:

  run_script:
    name: my script
    runs-on: ubuntu-latest
    steps:
      - name: docker?
        run: which docker && docker --version && docker-compose --version || true    
      - name: jq?
        run: which jq && jq --version || true    
      - name: perl?
        run: which perl && perl --version || true     
      - name: lua?
        run: which lua && lua -v || true      
      - name: go?
        run: which go && go version || true
      - name: node?
        run: which node && node --version || true
      - name: python?
        run: which python && python --version || true
      - name: php?
        run: which php && php --version || true        