name: Main

on:
  release:
    types:
      - created

jobs:

  run_script:
    name: my script
    runs-on: ubuntu-latest
    steps:
      - name: print 
        run: echo ${{ toJSON(github.ref_name) }}
