name: Release create

on:
  release:
    types:
      - created

jobs:

  run_script:
    name: my script
    runs-on: ubuntu-latest
    steps:
      - name: print 
        run: echo xxx "${{ toJSON(github.event.release.tag_name) }}" xxx
      - name: build
        run: head -c 1026 /dev/random | base64 > mybinary_${{github.ref_name}}.bin
      - name: upload binary as artifact
        run: gh release upload --repo ${{github.repository}} ${{github.ref_name}} mybinary_${{github.ref_name}}.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
